class <%= class_name.singularize.camelize %> < ActiveRecord::Base
# Code generated by MetaScaffold BEGIN
<% class_ass.each do |relation| -%>
  <%= relation.keys[0] %> :<%= (relation.keys[0] == "belongs_to" || relation.keys[0] == "has_one" )? relation.values[0].tableize.singularize : relation.values[0].tableize %>
<% end -%>
  
  include MetaRails::MetaScaffoldModelBaseMethods
# Code generated by MetaScaffold END

end
